CREATE TYPE [Pttcd].[CourseUploadRowTable] AS TABLE
(
	[RowNumber] INT NOT NULL,
	[IsValid] BIT NOT NULL,
	[Errors] VARCHAR(MAX),
	[LastUpdated] DATETIME,
	[LastValidated] DATETIME NOT NULL,
	[CourseId] UNIQUEIDENTIFIER,
	[CourseRunId] UNIQUEIDENTIFIER,
	[LarsQan] NVARCHAR(MAX),
	[WhoThisCourseIsFor] NVARCHAR(MAX),
	[EntryRequirements] NVARCHAR(MAX),
	[WhatYouWillLearn] NVARCHAR(MAX),
	[HowYouWillLearn] NVARCHAR(MAX),
	[WhatYouWillNeedToBring] NVARCHAR(MAX),
	[HowYouWillBeAssessed] NVARCHAR(MAX),
	[WhereNext] NVARCHAR(MAX),
	[CourseName] NVARCHAR(MAX),
	[YourReference] NVARCHAR(MAX),
	[DeliveryMode] NVARCHAR(MAX),
	[StartDate] NVARCHAR(MAX),
	[FlexibleStartDate] NVARCHAR(MAX),
	[VenueName] NVARCHAR(MAX),
	[ProviderVenueRef] NVARCHAR(MAX),
	[NationalDelivery] NVARCHAR(MAX),
	[SubRegions] NVARCHAR(MAX),
	[CourseWebpage] NVARCHAR(MAX),
	[Cost] NVARCHAR(MAX),
	[CostDescription] NVARCHAR(MAX),
	[Duration] NVARCHAR(MAX),
	[DurationUnit] NVARCHAR(MAX),
	[StudyMode] NVARCHAR(MAX),
	[AttendancePattern] NVARCHAR(MAX)
)
