CREATE TABLE [Pttcd].[ApprenticeshipUploadRows](
    [ApprenticeshipUploadRowId] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ApprenticeshipUploadRows] PRIMARY KEY,
    [ApprenticeshipUploadId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [FK_ApprenticeshipUploadRows_ApprenticeshipUploads] FOREIGN KEY REFERENCES [Pttcd].[ApprenticeshipUploads] ([ApprenticeshipUploadId]),
    [RowNumber] INT NOT NULL,
    [ApprenticeshipUploadRowStatus] TINYINT NOT NULL,
    [IsValid] BIT NOT NULL,
    [Errors] VARCHAR(max) NULL,
    [LastUpdated] DATETIME NOT NULL,
    [LastValidated] DATETIME NOT NULL,
    [ApprenticeshipId] UNIQUEIDENTIFIER,
    [ApprenticeshipLocationId] UNIQUEIDENTIFIER/* NOT NULL*/,
    [StandardCode] INT NOT NULL,
    [StandardVersion] INT NOT NULL,
    [ApprenticeshipInformation] NVARCHAR(MAX),
    [ApprenticeshipWebpage]  NVARCHAR(MAX),
    [ContactEmail] NVARCHAR(MAX),
    [ContactPhone] NVARCHAR(MAX),
    [ContactUrl] NVARCHAR(MAX),
    [DeliveryMethod] NVARCHAR(MAX),
    [VenueName] NVARCHAR(MAX),
    [YourVenueReference] NVARCHAR(MAX),
    [Radius] NVARCHAR(MAX),
    [DeliveryModes] NVARCHAR(MAX),
    [NationalDelivery] NVARCHAR(MAX),
    [SubRegions] NVARCHAR(MAX),
    [VenueId] UNIQUEIDENTIFIER CONSTRAINT [FK_ApprenticeshipUploadRows_Venue] FOREIGN KEY REFERENCES [Pttcd].[Venues] ([VenueId]),
    [ResolvedDeliveryMethod] TINYINT,
    [ResolvedDeliveryModes] TINYINT,
    [ResolvedNationalDelivery] BIT,
    [ResolvedRadius] INT,
)
