CREATE TABLE [Pttcd].[ApprenticeshipUploadRows](
    [ApprenticeshipUploadRowId] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ApprenticeshipUploadRows] PRIMARY KEY,
    [ApprenticeshipUploadId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [FK_ApprenticeshipUploadRows_ApprenticeshipUploads] FOREIGN KEY REFERENCES [Pttcd].[ApprenticeshipUploads] ([ApprenticeshipUploadId]),
    [RowNumber] INT NOT NULL,
    [ApprenticeshipUploadRowStatus] TINYINT NOT NULL,
    [IsValid] BIT NOT NULL,
    [Errors] VARCHAR(max) NULL,
    [LastUpdated] DATETIME NOT NULL,
    [LastValidated] DATETIME NOT NULL,
    [ApprenticeshipId] UNIQUEIDENTIFIER NOT NULL,
    [StandardCode] INT NOT NULL,
    [StandardVersion] INT NOT NULL,
    [ApprenticeshipInformation] NVARCHAR(MAX) NOT NULL,
    [ApprenticeshipWebpage]  NVARCHAR(MAX) NULL,
    [ContactEmail] NVARCHAR(MAX) NOT NULL,
    [ContactPhone] NVARCHAR(MAX) NOT NULL,
    [ContactUrl] NVARCHAR(MAX) NULL,
    [DeliveryMode] NVARCHAR(MAX) NOT NULL,
    [Venue] NVARCHAR(MAX) NULL,
    [YourVenueReference] NVARCHAR(MAX) NOT NULL,
    [Radius] NVARCHAR(MAX) NULL,
    [NationalDelivery] NVARCHAR(MAX) NULL,
    [SubRegions] NVARCHAR(MAX) NULL
)
