CREATE TABLE [Pttcd].[Users]
(
	[UserId] VARCHAR(100) NOT NULL CONSTRAINT [PK_Users] PRIMARY KEY,
	[Email] NVARCHAR(MAX) NOT NULL,
	[FirstName] NVARCHAR(MAX) NOT NULL,
	[LastName] NVARCHAR(MAX) NOT NULL
)
