CREATE NONCLUSTERED INDEX [IDX_CourseRuns_CourseRunStatus_CreatedOn] ON [Pttcd].[CourseRuns] ( [CourseRunStatus] ASC, [CreatedOn] ASC )WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

