CREATE NONCLUSTERED INDEX [nci_msft_CourseRuns_2BDFCF873B79949BC549A101C9BE3AC4] ON [Pttcd].[CourseRuns]
(
	[CourseRunStatus] ASC,
	[CreatedOn] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
