CREATE TABLE [ONSPD].[ONSPD_Ward] (
    [WD18CD]  NVARCHAR (50)  NOT NULL,
    [WD18NM]  NVARCHAR (MAX) NOT NULL,
    [WD18NMW] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ONSPD_Ward] PRIMARY KEY CLUSTERED ([WD18CD] ASC)
);

