CREATE TABLE [ONSPD].[ONSPD_Region] (
    [GOR10CD]  NVARCHAR (50) NOT NULL,
    [GOR10CDO] NVARCHAR (50) NULL,
    [GOR10NM]  NVARCHAR (50) NOT NULL,
    [GOR10NMW] NVARCHAR (50) NULL,
    CONSTRAINT [PK_ONSPD_Region] PRIMARY KEY CLUSTERED ([GOR10CD] ASC)
);

