CREATE TABLE [ONSPD].[ONSPD_NOV_2018_UK] (
    [pcd]       NVARCHAR (50) NOT NULL,
    [pcd2]      NVARCHAR (50) NOT NULL,
    [pcds]      NVARCHAR (50) NOT NULL,
    [dointr]    NVARCHAR (50) NOT NULL,
    [doterm]    NVARCHAR (50) NOT NULL,
    [oscty]     NVARCHAR (50) NOT NULL,
    [ced]       NVARCHAR (50) NOT NULL,
    [oslaua]    NVARCHAR (50) NOT NULL,
    [osward]    NVARCHAR (50) NOT NULL,
    [parish]    NVARCHAR (50) NOT NULL,
    [usertype]  NVARCHAR (50) NOT NULL,
    [oseast1m]  NVARCHAR (50) NOT NULL,
    [osnrth1m]  NVARCHAR (50) NOT NULL,
    [osgrdind]  NVARCHAR (50) NOT NULL,
    [oshlthau]  NVARCHAR (50) NOT NULL,
    [nhser]     NVARCHAR (50) NOT NULL,
    [ctry]      NVARCHAR (50) NOT NULL,
    [rgn]       NVARCHAR (50) NOT NULL,
    [streg]     NVARCHAR (50) NOT NULL,
    [pcon]      NVARCHAR (50) NOT NULL,
    [eer]       NVARCHAR (50) NOT NULL,
    [teclec]    NVARCHAR (50) NOT NULL,
    [ttwa]      NVARCHAR (50) NOT NULL,
    [pct]       NVARCHAR (50) NOT NULL,
    [nuts]      NVARCHAR (50) NOT NULL,
    [statsward] NVARCHAR (50) NOT NULL,
    [oa01]      NVARCHAR (50) NOT NULL,
    [casward]   NVARCHAR (50) NOT NULL,
    [park]      NVARCHAR (50) NOT NULL,
    [lsoa01]    NVARCHAR (50) NOT NULL,
    [msoa01]    NVARCHAR (50) NOT NULL,
    [ur01ind]   NVARCHAR (50) NOT NULL,
    [oac01]     NVARCHAR (50) NOT NULL,
    [oa11]      NVARCHAR (50) NOT NULL,
    [lsoa11]    NVARCHAR (50) NOT NULL,
    [msoa11]    NVARCHAR (50) NOT NULL,
    [wz11]      NVARCHAR (50) NOT NULL,
    [ccg]       NVARCHAR (50) NOT NULL,
    [bua11]     NVARCHAR (50) NOT NULL,
    [buasd11]   NVARCHAR (50) NOT NULL,
    [ru11ind]   NVARCHAR (50) NOT NULL,
    [oac11]     NVARCHAR (50) NOT NULL,
    [lat]       FLOAT (53)    NOT NULL,
    [long]      FLOAT (53)    NOT NULL,
    [lep1]      NVARCHAR (50) NOT NULL,
    [lep2]      NVARCHAR (50) NOT NULL,
    [pfa]       NVARCHAR (50) NOT NULL,
    [imd]       INT           NOT NULL,
    [calncv]    NVARCHAR (50) NOT NULL,
    [stp]       NVARCHAR (50) NOT NULL,
    [updated]   DATETIME      NULL,
    CONSTRAINT [PK_ONSPD_NOV_2018_UK] PRIMARY KEY CLUSTERED ([pcd] ASC)
);

