variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Dfc.CourseDirectory.Api\Resources\ArmTemplates'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  SolutionBaseName: 'Dfc.CourseDirectory.Api'
  GitVersionConfigFilePath: Dfc.CourseDirectory.Api/Resources/AzureDevOps/GitVersion.yml
  group: dfc-coursedirectory-api-build

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.14.0

pool:
  name: NCS - CI and CD
  demands:
  - azureps

trigger:
  batch: true
  branches:
    include:
    - release/*
    - main
  paths:
    include:
    - Dfc.CourseDirectory.Api/*
    - Dfc.CourseDirectory.Core/*
    - Dfc.CourseDirectory.Database/*
    - Dfc.CourseDirectory.Api/*
    - Dfc.CourseDirectory.Core.Tests/*
    - Dfc.CourseDirectory.Testing/*

pr:
  branches:
    include:
    - release/*
    - main
    - develop
  paths:
    include:
    - Dfc.CourseDirectory.Api/*
    - Dfc.CourseDirectory.Core/*
    - Dfc.CourseDirectory.Database/*
    - Dfc.CourseDirectory.Api/*
    - Dfc.CourseDirectory.Core.Tests/*
    - Dfc.CourseDirectory.Testing/*

workspace:
  clean: all

steps:

- task: UseGitVersion@5
  displayName: GitVersion
  inputs:
    useConfigFile: true
    configFilePath: ${{ variables.GitVersionConfigFilePath }}
    versionSpec: '5.3.x'

# ARM template
- template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
  parameters:
    ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
    SolutionBaseName: '${{ variables.SolutionBaseName }}'

- task: PublishBuildArtifacts@1
  displayName: Publish AzureSearch files
  inputs:
     pathtoPublish: 'Dfc.CourseDirectory.Api/Resources/AzureSearch'
     artifactName: '$(SolutionBaseName).Resources.AzureSearch'

- task: MSBuild@1
  displayName: Build database
  inputs:
    solution: 'Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj'
    platform: '${{ variables.BuildPlatform }}'
    configuration: '${{ variables.BuildConfiguration }}'
    msbuildArguments: '-p:OutputPath=bin/${{ variables.BuildConfiguration }}/'

# Remove the sqlproj from the solution otherwise `dotnet build Dfc.CourseDirectory.Api.sln` explodes
- powershell: |
    dotnet sln Dfc.CourseDirectory.Api/$(SolutionBaseName).sln remove Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Dfc.CourseDirectory.Api/$(SolutionBaseName).sln'
    arguments: '--configuration ${{ variables.BuildConfiguration }}'
  displayName: Build

- task: DotNetCoreCLI@2
  displayName: Publish Dfc.CourseDirectory.Api
  inputs:
    command: publish
    projects: 'Dfc.CourseDirectory.Api/Dfc.CourseDirectory.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    publishWebProjects: false
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: '${{ variables.SolutionBaseName }}'
