//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dfc.CourseDirectory.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dfc.CourseDirectory.Core.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 must only include letters a to z, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 must be {0} characters or less.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address line 1.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 must only include letters a to z, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE2_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE2_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 must be {0} characters or less.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE2_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE2_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County must only include letters a to z, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_COUNTY_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_COUNTY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County must be {0} characters or less.
        /// </summary>
        public static string ERROR_VENUE_COUNTY_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_COUNTY_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address in the correct format.
        /// </summary>
        public static string ERROR_VENUE_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue name must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_NAME_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter venue name.
        /// </summary>
        public static string ERROR_VENUE_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue name must not already exist.
        /// </summary>
        public static string ERROR_VENUE_NAME_UNIQUE {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a real postcode.
        /// </summary>
        public static string ERROR_VENUE_POSTCODE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_POSTCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a postcode.
        /// </summary>
        public static string ERROR_VENUE_POSTCODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_POSTCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your venue reference must be {0} characters or less.
        /// </summary>
        public static string ERROR_VENUE_PROVIDER_VENUE_REF_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_PROVIDER_VENUE_REF_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your venue reference must be unique.
        /// </summary>
        public static string ERROR_VENUE_PROVIDER_VENUE_REF_UNIQUE {
            get {
                return ResourceManager.GetString("ERROR_VENUE_PROVIDER_VENUE_REF_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a telephone number in the correct format.
        /// </summary>
        public static string ERROR_VENUE_TELEPHONE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TELEPHONE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city must only include letters a to z, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_TOWN_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city must be {0} characters or less.
        /// </summary>
        public static string ERROR_VENUE_TOWN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a town or city.
        /// </summary>
        public static string ERROR_VENUE_TOWN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a website in the correct format.
        /// </summary>
        public static string ERROR_VENUE_WEBSITE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_WEBSITE_FORMAT", resourceCulture);
            }
        }
    }
}
