//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dfc.CourseDirectory.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dfc.CourseDirectory.Core.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry requirements must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_ENTRY_REQUIREMENTS_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_ENTRY_REQUIREMENTS_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How you&apos;ll be assesssed must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_HOW_YOU_WILL_BE_ASSESSED_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_HOW_YOU_WILL_BE_ASSESSED_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How you&apos;ll learn must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_HOW_YOU_WILL_LEARN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_HOW_YOU_WILL_LEARN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_LARS_QAN_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSE_LARS_QAN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_LARS_QAN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSE_LARS_QAN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you can do next must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_CAN_DO_NEXT_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_CAN_DO_NEXT_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you&apos;ll learn must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_WILL_LEARN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_WILL_LEARN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_WILL_NEED_TO_BRING_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_WILL_NEED_TO_BRING_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHERE_NEXT_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHERE_NEXT_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter who this course is for.
        /// </summary>
        public static string ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_ATTENDANCE_PATTERN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_ATTENDANCE_PATTERN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_ATTENDANCE_PATTERN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_ATTENDANCE_PATTERN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_DESCRIPTION_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_DESCRIPTION_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_WEB_PAGE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_WEB_PAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_WEB_PAGE_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_WEB_PAGE_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DELIVERY_MODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DELIVERY_MODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_RANGE {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_UNIT_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_UNIT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_FLEXIBLE_START_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_FLEXIBLE_START_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_NATIONAL_DELIVERY_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_NATIONAL_DELIVERY_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_NATIONAL_DELIVERY_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_NATIONAL_DELIVERY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_COURSE_REF_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_COURSE_REF_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_COURSE_REF_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_COURSE_REF_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_VENUE_REF_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_VENUE_REF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_VENUE_REF_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_VENUE_REF_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_STUDY_MODE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_STUDY_MODE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_STUDY_MODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_STUDY_MODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED_WITH_REF {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED_WITH_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry requirements must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_ENTRY_REQUIREMENTS_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_ENTRY_REQUIREMENTS_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How you&apos;ll be assesssed must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_HOW_YOU_WILL_BE_ASSESSED_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_HOW_YOU_WILL_BE_ASSESSED_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How you&apos;ll learn must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_HOW_YOU_WILL_LEARN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_HOW_YOU_WILL_LEARN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_LARS_QAN_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSE_LARS_QAN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_LARS_QAN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSE_LARS_QAN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you can do next must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_CAN_DO_NEXT_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_CAN_DO_NEXT_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you&apos;ll learn must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_WILL_LEARN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_WILL_LEARN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHAT_YOU_WILL_NEED_TO_BRING_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHAT_YOU_WILL_NEED_TO_BRING_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHERE_NEXT_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHERE_NEXT_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter who this course is for.
        /// </summary>
        public static string ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSE_WHO_THIS_COURSE_IS_FOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_ATTENDANCE_PATTERN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_ATTENDANCE_PATTERN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_ATTENDANCE_PATTERN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_ATTENDANCE_PATTERN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_DESCRIPTION_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_DESCRIPTION_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_DESCRIPTION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_DESCRIPTION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COST_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COST_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_WEB_PAGE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_WEB_PAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_COURSE_WEB_PAGE_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_COURSE_WEB_PAGE_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DELIVERY_MODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DELIVERY_MODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_RANGE {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_DURATION_UNIT_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_DURATION_UNIT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_FLEXIBLE_START_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_FLEXIBLE_START_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_NATIONAL_DELIVERY_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_NATIONAL_DELIVERY_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_NATIONAL_DELIVERY_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_NATIONAL_DELIVERY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_COURSE_REF_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_COURSE_REF_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_COURSE_REF_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_COURSE_REF_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_VENUE_REF_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_VENUE_REF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_PROVIDER_VENUE_REF_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_PROVIDER_VENUE_REF_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_START_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_START_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_STUDY_MODE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_STUDY_MODE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_STUDY_MODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_STUDY_MODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_SUBREGIONS_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_SUBREGIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED_WITH_REF {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_NAME_NOT_ALLOWED_WITH_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TODO&gt;.
        /// </summary>
        public static string ERROR_COURSERUN_VENUE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_COURSERUN_VENUE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 must only include letters, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address for your venue.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE1_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE1_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 must only include letters, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE2_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE2_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_ADDRESS_LINE2_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_ADDRESS_LINE2_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County must only include letters, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_COUNTY_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_COUNTY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_COUNTY_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_COUNTY_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address in the correct format.
        /// </summary>
        public static string ERROR_VENUE_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue name must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_NAME_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name for your venue.
        /// </summary>
        public static string ERROR_VENUE_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue name must be unique.
        /// </summary>
        public static string ERROR_VENUE_NAME_UNIQUE {
            get {
                return ResourceManager.GetString("ERROR_VENUE_NAME_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a real postcode for your venue.
        /// </summary>
        public static string ERROR_VENUE_POSTCODE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_POSTCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a postcode for your venue.
        /// </summary>
        public static string ERROR_VENUE_POSTCODE_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_POSTCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your venue reference must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_PROVIDER_VENUE_REF_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_PROVIDER_VENUE_REF_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a reference for your venue.
        /// </summary>
        public static string ERROR_VENUE_PROVIDER_VENUE_REF_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_PROVIDER_VENUE_REF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your venue reference must be unique.
        /// </summary>
        public static string ERROR_VENUE_PROVIDER_VENUE_REF_UNIQUE {
            get {
                return ResourceManager.GetString("ERROR_VENUE_PROVIDER_VENUE_REF_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a phone number in the correct format.
        /// </summary>
        public static string ERROR_VENUE_TELEPHONE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TELEPHONE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city must only include letters, numbers, hyphens and spaces.
        /// </summary>
        public static string ERROR_VENUE_TOWN_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city must be {0} characters or fewer.
        /// </summary>
        public static string ERROR_VENUE_TOWN_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a town or city.
        /// </summary>
        public static string ERROR_VENUE_TOWN_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_VENUE_TOWN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a website in the correct format.
        /// </summary>
        public static string ERROR_VENUE_WEBSITE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VENUE_WEBSITE_FORMAT", resourceCulture);
            }
        }
    }
}
